<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3Y60xz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3Y60xz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB3Y60xz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB3Y60xz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB3Y60xz\App_KernelDevDebugContainer([
    'container.build_hash' => 'B3Y60xz',
    'container.build_id' => 'bb8d8412',
    'container.build_time' => 1590770473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3Y60xz');
