<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPbPkJUA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPbPkJUA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPbPkJUA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPbPkJUA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPbPkJUA\App_KernelDevDebugContainer([
    'container.build_hash' => 'PbPkJUA',
    'container.build_id' => '092452fb',
    'container.build_time' => 1590622288,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPbPkJUA');
